#!/bin/zsh
#
# Script to make a library of models to be served.
#
# The script will:
#
# 1. Search for `*.poieticframe` source files in `FRAMES_PATH` (default: `../PoieticExamples`)
# 2. Creates a design file for each frame.
# 3. Creates a library `poietic-library.json` in current directory.
#
# Requires: poietic tool from PoieticFlows to be available in PATH.
#
# Usage:
#
# ./create-examples-library
#
# With explicit path:
#
# FRAMES_PATH=MyFrames ./create-examples-library
#

set -e

# -----------------------------------------------------------------------------------
# Some internal config, you might skip this to the next section ...

# Path to the poietic tool.
#
# If this demo project directory share the same parent directory as the Poietic Core,
# then make sure that the tool has been built and run this command using:
#
# POIETIC=../PoieticCore/.build/debug/poietic ./run PATH_TO_BUDNLE.poieticframe
# 
POIETIC="${POIETIC:-poietic}"

# Path to the output directory, default ./out
OUTPUT_DIR="${OUTPUT:-./ModelLibrary}"
FRAMES_PATH="${FRAMES_PATH:-../PoieticExamples}"

if ! command -v ${POIETIC} &> /dev/null
then
	echo "ERROR: Poietic command '${TOOL}' not found. Set POIETIC environment variable with a valid executable path." 1>&2
    echo "HINT: If you built PoieticFlows, then the executable is likely '.build/debug/poietic' in PoieticFlows directory" 1>&2
    echo "HINT: Try 'export POIETIC=../PoieticFlows/.build/debug/poietic' if the PoieticFlows is in the super directory relative to this one" 1>&2
	exit 1
fi


echo "Creating ${OUTPUT_DIR}"
mkdir -p "${OUTPUT_DIR}"

all_frames=($(find $FRAMES_PATH -name '*.poieticframe' ))

for frame_path in ${all_frames[*]}; do
    frame_name=$(basename -- $frame_path)
    frame_name=${frame_name%.*}

    export POIETIC_DESIGN="$OUTPUT_DIR/${frame_name}.poietic"
    echo "Processing frame ${frame_name}"
    $POIETIC new --import $frame_path --auto-parameters
done

# FINALLY: Create the library!
#
echo "Creating library..."
poietic create-library $OUTPUT_DIR/*.poietic
